# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowLecteurVideo.ui',
# licensing of 'MainWindowLecteurVideo.ui' applies.
#
# Created: Thu Jul 18 09:54:10 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(972, 669)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.videoWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoWidget.sizePolicy().hasHeightForWidth())
        self.videoWidget.setSizePolicy(sizePolicy)
        self.videoWidget.setObjectName("videoWidget")
        self.verticalLayout_4.addWidget(self.videoWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.TempsPasse = QtWidgets.QLabel(self.centralwidget)
        self.TempsPasse.setObjectName("TempsPasse")
        self.horizontalLayout_3.addWidget(self.TempsPasse)
        self.sTempsCourant = QtWidgets.QSlider(self.centralwidget)
        self.sTempsCourant.setMinimumSize(QtCore.QSize(0, 40))
        self.sTempsCourant.setOrientation(QtCore.Qt.Horizontal)
        self.sTempsCourant.setObjectName("sTempsCourant")
        self.horizontalLayout_3.addWidget(self.sTempsCourant)
        self.TempsTotal = QtWidgets.QLabel(self.centralwidget)
        self.TempsTotal.setObjectName("TempsTotal")
        self.horizontalLayout_3.addWidget(self.TempsTotal)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbLecture = QtWidgets.QPushButton(self.centralwidget)
        self.pbLecture.setObjectName("pbLecture")
        self.horizontalLayout_2.addWidget(self.pbLecture)
        self.pbPause = QtWidgets.QPushButton(self.centralwidget)
        self.pbPause.setObjectName("pbPause")
        self.horizontalLayout_2.addWidget(self.pbPause)
        self.pbStop = QtWidgets.QPushButton(self.centralwidget)
        self.pbStop.setObjectName("pbStop")
        self.horizontalLayout_2.addWidget(self.pbStop)
        self.pbPrec = QtWidgets.QPushButton(self.centralwidget)
        self.pbPrec.setObjectName("pbPrec")
        self.horizontalLayout_2.addWidget(self.pbPrec)
        self.pbSuiv = QtWidgets.QPushButton(self.centralwidget)
        self.pbSuiv.setObjectName("pbSuiv")
        self.horizontalLayout_2.addWidget(self.pbSuiv)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(20, 85, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.listeLecture = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listeLecture.sizePolicy().hasHeightForWidth())
        self.listeLecture.setSizePolicy(sizePolicy)
        self.listeLecture.setObjectName("listeLecture")
        self.verticalLayout_8.addWidget(self.listeLecture)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.pbAjouter = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbAjouter.sizePolicy().hasHeightForWidth())
        self.pbAjouter.setSizePolicy(sizePolicy)
        self.pbAjouter.setObjectName("pbAjouter")
        self.horizontalLayout_5.addWidget(self.pbAjouter)
        self.pbSupprimer = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbSupprimer.sizePolicy().hasHeightForWidth())
        self.pbSupprimer.setSizePolicy(sizePolicy)
        self.pbSupprimer.setObjectName("pbSupprimer")
        self.horizontalLayout_5.addWidget(self.pbSupprimer)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setMaximumSize(QtCore.QSize(50, 50))
        self.dial.setObjectName("dial")
        self.horizontalLayout_6.addWidget(self.dial)
        self.Volume = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Volume.sizePolicy().hasHeightForWidth())
        self.Volume.setSizePolicy(sizePolicy)
        self.Volume.setObjectName("Volume")
        self.horizontalLayout_6.addWidget(self.Volume)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 972, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.TempsPasse.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.TempsTotal.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.pbLecture.setText(QtWidgets.QApplication.translate("MainWindow", "Lecture", None, -1))
        self.pbPause.setText(QtWidgets.QApplication.translate("MainWindow", "Pause", None, -1))
        self.pbStop.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.pbPrec.setText(QtWidgets.QApplication.translate("MainWindow", "Precedent", None, -1))
        self.pbSuiv.setText(QtWidgets.QApplication.translate("MainWindow", "Suivant", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Liste de lecture :", None, -1))
        self.pbAjouter.setText(QtWidgets.QApplication.translate("MainWindow", "+", None, -1))
        self.pbSupprimer.setText(QtWidgets.QApplication.translate("MainWindow", "-", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Volume :", None, -1))
        self.Volume.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))

